"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/1.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/2.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/3.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/4.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/5.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/6.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/7.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/8.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/9.jpg --model_name stereo_1024x320
"C:\Users\Muhammad  Wajeeh\Desktop\MonoDepth\python.exe" test_simple.py --image_path assets/10.jpg --model_name stereo_1024x320